[build]
  # Directory to change to before starting a build
  base = "swift_hire/frontend"

  # Directory that contains the deploy-ready HTML files and assets
  publish = "swift_hire/frontend/build"

  # Default build command
  command = "npm install && npm run build"

# Redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
