[build]
  # Directory to change to before starting a build
  base = "swift_hire/frontend"

  # Directory that contains the deploy-ready HTML files and assets
  publish = "build"

  # Default build command
  command = "npm install && npm run build"

# Redirect rules for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Backend API URL - Replace with your actual Railway URL
  REACT_APP_API_BASE_URL = "https://swift-hire-production.up.railway.app"
  # Google API keys
  REACT_APP_GOOGLE_API_KEY = "AIzaSyB3y_5UUBD76kJpwp3AlCQ2tJnsAzyaZZo"
  REACT_APP_GOOGLE_CLIENT_ID = "1089449035363-k9rrcoueo8q4f0mf652q42n7h4j6dk6l.apps.googleusercontent.com"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
