services:
  - type: web
    name: swift-hire-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: swift-hire-db
          property: connectionString

databases:
  - name: swift-hire-db
    databaseName: swift_hire
    user: swift_hire_user
